Added Error when no content
MichaelKavanagh/elexon pull request #6
Opened 2021-03-12 06:11 UTC by pfreiberger

The code was raising a generic exception whenever status code is not 200. However, often the code is 204 which indicates that the request wa ssuccessful but no contet is available. I added a few lines to raise a NoContentException is one can easily catch these types of exceptions

2021-03-15 11:05 UTC, MichaelKavanagh requested changes
Hi!

Thank you for your PR, in general these changes look good to me. 

I've left one small formatting request, but otherwise I am happy to merge this.

Thanks.

2021-03-15 11:05 UTC, MichaelKavanagh commented on elexon/elexon.py
> +        if r_httpCode == "204":
Please can you change these to single quotes for consistency?

2021-03-17 05:50 UTC, pfreiberger commented on elexon/elexon.py
> +        if r_httpCode == "204":
Just pushed the change below

2021-03-17 10:51 UTC, merged

2021-03-17 10:55 UTC, MichaelKavanagh commented
Great, thank you for your contribution!